pipeline:
  run-mongo-tests:
    image: node:10.11.0
    commands:
      - ./bin/run.sh
    when:
      status: [ failure, success ]
      event: [pull_request]

  run-coveralls:
    image: node:10.11.0
    secrets: [ coveralls_service_name, coveralls_repo_token ]
    commands:
      - sleep 5
      - ./bin/run-coveralls.sh
    when:
      event: [ pull_request ]
      branches: [ master ]

  publish-node-mongo:
    image: plugins/npm
    secrets: [ npm_username, npm_email, npm_password ]
    when:
      event: [ tag ]
      branches: [ master ]

services:
  mongo:
    image: mongo:4.0.3
branches: [ master, "*:master" ]
