kind: pipeline
name: default

steeps:
- name: run-mongo-tests
  image: node:10.16.0
  commands:
    - chmod +x ./bin/run.sh
    - ./bin/run.sh
  when:
    event:
    - pull_request
    - push

- name: run-coveralls
  image: node:10.16.0
    secrets: [ coveralls_repo_token ]
  commands:
    - sleep 5
    - chmod +x ./bin/run-coveralls.sh
    - ./bin/run-coveralls.sh
  environment:
    COVERALLS_REPO_TOKEN:
      from_secret: coveralls_repo_token
  when:
    event:
    - pull_request
    - push
    status:
    - success

- name: publish-node-mongo
  image: plugins/npm
  settings:
    username:
      from_secret: npm_username
    password:
      from_secret: npm_password
    email:
      from_secret: npm_email
  when:
    event:
    - tag
    branches:
    - master
    status:
    - success

services:
- name: mongo
  image: mongo:4.0.10

trigger:
  branch:
  - master
